Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 07:06:33
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[06/Sep/2024 07:06:50] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:06:51] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:06:52] "GET /common/login/ HTTP/1.1" 200 2460
Internal Server Error: /common/signup/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/common/views.py", line 21, in signup
    return render(request, 'common/signup.html', {'form': form})
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: common/signup.html
[06/Sep/2024 07:07:39] "GET /common/signup/ HTTP/1.1" 500 74467
[06/Sep/2024 07:16:35,943] - Broken pipe from ('162.142.125.212', 37352)
[06/Sep/2024 07:16:39] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:16:39,984] - Broken pipe from ('162.142.125.212', 37430)
[06/Sep/2024 07:16:43] "GET / HTTP/1.1" 200 7605
Not Found: /favicon.ico
[06/Sep/2024 07:16:44] "GET /favicon.ico HTTP/1.1" 404 2442
[06/Sep/2024 07:16:44] code 505, message Invalid HTTP version (2.0)
[06/Sep/2024 07:16:44] "PRI * HTTP/2.0" 505 -
[06/Sep/2024 07:29:19] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:29:20] "GET /common/signup/ HTTP/1.1" 200 2891
[06/Sep/2024 07:35:03] "GET /common/signup/ HTTP/1.1" 200 2891
[06/Sep/2024 07:35:16,690] - Broken pipe from ('162.142.125.42', 36610)
[06/Sep/2024 07:35:19] "POST /common/signup/ HTTP/1.1" 200 3373
[06/Sep/2024 07:35:19] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:35:20,104] - Broken pipe from ('162.142.125.42', 36620)
[06/Sep/2024 07:35:25] "GET / HTTP/1.1" 200 7605
Not Found: /favicon.ico
[06/Sep/2024 07:35:26] "GET /favicon.ico HTTP/1.1" 404 2442
[06/Sep/2024 07:35:26] "POST /common/signup/ HTTP/1.1" 302 0
[06/Sep/2024 07:35:26] code 505, message Invalid HTTP version (2.0)
[06/Sep/2024 07:35:26] "PRI * HTTP/2.0" 505 -
[06/Sep/2024 07:35:26] "GET / HTTP/1.1" 200 7515
[06/Sep/2024 07:35:37] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 07:35:37] "GET / HTTP/1.1" 200 7605
[06/Sep/2024 07:35:38] "GET /common/login/ HTTP/1.1" 200 2460
[06/Sep/2024 07:35:39] "GET /common/signup/ HTTP/1.1" 200 2891
[06/Sep/2024 07:35:50] "POST /common/signup/ HTTP/1.1" 200 3304
[06/Sep/2024 07:36:54] "POST /common/signup/ HTTP/1.1" 302 0
[06/Sep/2024 07:36:54] "GET / HTTP/1.1" 200 7516
[06/Sep/2024 07:36:58] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3701
[06/Sep/2024 07:36:58] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
[06/Sep/2024 07:36:58] "GET /static/admin/css/base.css HTTP/1.1" 200 21310
[06/Sep/2024 07:36:58] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
[06/Sep/2024 07:36:58] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[06/Sep/2024 07:36:58] "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
[06/Sep/2024 07:36:58] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
[06/Sep/2024 07:36:58] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[06/Sep/2024 07:37:01] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[06/Sep/2024 07:37:01] "GET /admin/ HTTP/1.1" 200 7241
[06/Sep/2024 07:37:01] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[06/Sep/2024 07:37:01] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[06/Sep/2024 07:37:01] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[06/Sep/2024 07:37:06] "GET /admin/auth/user/ HTTP/1.1" 200 12057
[06/Sep/2024 07:37:06] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
[06/Sep/2024 07:37:06] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[06/Sep/2024 07:37:06] "GET /static/admin/js/core.js HTTP/1.1" 200 5682
[06/Sep/2024 07:37:06] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
[06/Sep/2024 07:37:06] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[06/Sep/2024 07:37:06] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[06/Sep/2024 07:37:06] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[06/Sep/2024 07:37:06] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
[06/Sep/2024 07:37:06] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[06/Sep/2024 07:37:06] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[06/Sep/2024 07:37:06] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[06/Sep/2024 07:37:06] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[06/Sep/2024 07:37:06] "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[06/Sep/2024 07:37:06] "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[06/Sep/2024 07:37:06] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[06/Sep/2024 07:37:06] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[06/Sep/2024 07:37:09] "GET /admin/ HTTP/1.1" 200 7241
/home/ec2-user/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 07:57:56
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/home/ec2-user/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:00:00
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:01:27
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:01:40
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:03:29
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[06/Sep/2024 08:03:30] "GET / HTTP/1.1" 200 7516
[06/Sep/2024 08:03:35] "GET /myapp/myapp/303/ HTTP/1.1" 200 2789
[06/Sep/2024 08:03:39] "POST /myapp/answer/create/303/ HTTP/1.1" 302 0
[06/Sep/2024 08:03:39] "GET /myapp/myapp/303/ HTTP/1.1" 200 3165
[06/Sep/2024 08:03:41] "GET /myapp/ HTTP/1.1" 200 7595
[06/Sep/2024 08:03:42] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 08:03:43] "GET / HTTP/1.1" 200 7684
[06/Sep/2024 08:03:43] "GET /common/login/ HTTP/1.1" 200 2460
[06/Sep/2024 08:03:48] "POST /common/login/ HTTP/1.1" 302 0
[06/Sep/2024 08:03:49] "GET / HTTP/1.1" 200 7594
[06/Sep/2024 08:03:52] "GET /myapp/myapp/300/ HTTP/1.1" 200 2788
[06/Sep/2024 08:03:56] "POST /myapp/answer/create/300/ HTTP/1.1" 302 0
[06/Sep/2024 08:03:56] "GET /myapp/myapp/300/ HTTP/1.1" 200 3172
[06/Sep/2024 08:03:58] "GET /myapp/ HTTP/1.1" 200 7673
[06/Sep/2024 08:03:59] "GET /myapp/question/create/ HTTP/1.1" 200 2435
[06/Sep/2024 08:04:04] "POST /myapp/question/create/ HTTP/1.1" 302 0
[06/Sep/2024 08:04:04] "GET /myapp/ HTTP/1.1" 200 7669
[06/Sep/2024 08:04:49] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 08:04:49] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 08:04:50] "GET /myapp/question/create/ HTTP/1.1" 200 2525
Internal Server Error: /myapp/question/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/myapp/views.py", line 44, in question_create
    question.author = request.user  # author 속성에 로그인 계정 저장
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f0a58599a90>>": "Question.author" must be a "User" instance.
[06/Sep/2024 08:04:53] "POST /myapp/question/create/ HTTP/1.1" 500 66938
[06/Sep/2024 08:04:56] "GET /myapp/ HTTP/1.1" 200 7759
[06/Sep/2024 08:04:56] "GET /myapp/myapp/304/ HTTP/1.1" 200 3244
Internal Server Error: /myapp/answer/create/304/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/myapp/views.py", line 29, in answer_create
    answer.author = request.user  # author 속성에 로그인 계정 저장
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f0a5858ea60>>": "Answer.author" must be a "User" instance.
[06/Sep/2024 08:04:58] "POST /myapp/answer/create/304/ HTTP/1.1" 500 67264
[06/Sep/2024 08:05:00] "GET /myapp/ HTTP/1.1" 200 7759
/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:06:26
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[06/Sep/2024 08:06:45] "GET /myapp/question/create/ HTTP/1.1" 302 0
[06/Sep/2024 08:06:45] "GET /common/login/?next=/myapp/question/create/ HTTP/1.1" 200 2460
[06/Sep/2024 08:06:47] "GET /myapp/myapp/305/ HTTP/1.1" 200 2896
[06/Sep/2024 08:06:50] "POST /myapp/answer/create/305/ HTTP/1.1" 302 0
[06/Sep/2024 08:06:50] "GET /common/login/?next=/myapp/answer/create/305/ HTTP/1.1" 200 2460
[06/Sep/2024 08:06:51] "GET /myapp/ HTTP/1.1" 200 7759
[06/Sep/2024 08:06:52] "GET /myapp/myapp/305/ HTTP/1.1" 200 2896
[06/Sep/2024 08:06:57] "GET /myapp/question/create/ HTTP/1.1" 302 0
[06/Sep/2024 08:06:57] "GET /common/login/?next=/myapp/question/create/ HTTP/1.1" 200 2460
[06/Sep/2024 08:07:26] "POST /common/login/ HTTP/1.1" 302 0
[06/Sep/2024 08:07:26] "GET / HTTP/1.1" 200 7670
[06/Sep/2024 08:07:31] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 08:07:31] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 08:08:03] "GET /myapp/question/create/ HTTP/1.1" 302 0
[06/Sep/2024 08:08:03] "GET /common/login/?next=/myapp/question/create/ HTTP/1.1" 200 2581
[06/Sep/2024 08:08:06] "POST /common/login/ HTTP/1.1" 302 0
[06/Sep/2024 08:08:06] "GET /myapp/question/create/ HTTP/1.1" 200 2436
[06/Sep/2024 08:08:08] "GET /common/login/?next=/myapp/question/create/ HTTP/1.1" 200 2492
[06/Sep/2024 08:08:11] "GET /myapp/ HTTP/1.1" 200 7670
[06/Sep/2024 08:11:46] "GET /myapp/ HTTP/1.1" 200 7670
[06/Sep/2024 08:11:48] "GET /myapp/myapp/296/ HTTP/1.1" 200 2802
[06/Sep/2024 08:11:50] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 08:11:50] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 08:11:51] "GET /myapp/myapp/296/ HTTP/1.1" 200 2899
[06/Sep/2024 08:11:55] "POST /myapp/answer/create/296/ HTTP/1.1" 302 0
[06/Sep/2024 08:11:55] "GET /common/login/?next=/myapp/answer/create/296/ HTTP/1.1" 200 2583
[06/Sep/2024 08:11:57] "POST /common/login/ HTTP/1.1" 302 0
Method Not Allowed: /myapp/answer/create/296/
[06/Sep/2024 08:11:57] "GET /myapp/answer/create/296/ HTTP/1.1" 405 0
[06/Sep/2024 08:11:59] "GET /common/login/?next=/myapp/answer/create/296/ HTTP/1.1" 200 2494
[06/Sep/2024 08:11:59] "GET /myapp/ HTTP/1.1" 200 7670
[06/Sep/2024 08:12:00] "GET /common/logout/ HTTP/1.1" 302 0
[06/Sep/2024 08:12:00] "GET / HTTP/1.1" 200 7759
/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2024 - 08:13:08
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[06/Sep/2024 08:13:13] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 08:13:14] "GET /myapp/myapp/305/ HTTP/1.1" 200 2917
[06/Sep/2024 08:13:16] "POST /myapp/answer/create/305/ HTTP/1.1" 302 0
[06/Sep/2024 08:13:16] "GET /common/login/?next=/myapp/answer/create/305/ HTTP/1.1" 200 2583
[06/Sep/2024 08:13:18] "POST /common/login/ HTTP/1.1" 302 0
[06/Sep/2024 08:13:18] "GET /myapp/answer/create/305/ HTTP/1.1" 200 2820
Not Found: /.env
[06/Sep/2024 08:44:11] "GET /.env HTTP/1.1" 404 2421
[06/Sep/2024 12:56:53,470] - Broken pipe from ('167.94.146.52', 43064)
[06/Sep/2024 12:56:58] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 12:56:58,615] - Broken pipe from ('167.94.146.52', 43150)
[06/Sep/2024 12:57:02] "GET / HTTP/1.1" 200 7759
Not Found: /favicon.ico
[06/Sep/2024 12:57:03] "GET /favicon.ico HTTP/1.1" 404 2442
[06/Sep/2024 12:57:04] code 505, message Invalid HTTP version (2.0)
[06/Sep/2024 12:57:04] "PRI * HTTP/2.0" 505 -
[06/Sep/2024 14:18:15] code 400, message Bad request version ('ò\x8aB\x118Ñ')
[06/Sep/2024 14:18:15] You're accessing the development server over HTTPS, but it only supports HTTP.
[06/Sep/2024 14:18:15] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03éå~\x96\x82.^\x9e{ã\x90¸v¿û\x16%\x17*Ôèpô\x8dë\x02ÌdÀ>.é\x00\x00hÌ\x14Ì\x13À/À+À0À,À\x11À\x07À'À#À\x13À")
[06/Sep/2024 14:18:15] You're accessing the development server over HTTPS, but it only supports HTTP.
[06/Sep/2024 15:54:34] code 400, message Bad request syntax ('MGLNDD_3.38.84.194_8000')
[06/Sep/2024 15:54:34] "MGLNDD_3.38.84.194_8000" 400 -
[06/Sep/2024 19:52:03] code 400, message Bad request version ('À\x14À')
[06/Sep/2024 19:52:03] You're accessing the development server over HTTPS, but it only supports HTTP.
[06/Sep/2024 19:52:03] code 400, message Bad request version ('À\x14À')
[06/Sep/2024 19:52:03] You're accessing the development server over HTTPS, but it only supports HTTP.
[06/Sep/2024 19:52:03] "GET / HTTP/1.1" 200 7759
Not Found: /login
[06/Sep/2024 19:52:04] "GET /login HTTP/1.1" 404 2424
[06/Sep/2024 23:01:06] code 400, message Bad request version ('ò\x0f\x02\x03\x01\x00\x01')
[06/Sep/2024 23:01:06] "   àZ          =K    |¨À PV¦9þ                                                 0 §¹ºùÃ:2ì}F`ý¼çW­âïÕôj¹¾Cñ ÆëòWè2ãWÎs+dÒÝ 7®ÕtçøgÀâæ¯Ço"¶R°á_¯	ÌçmÓýó"«cÈÒ#oìS{?ªW¬HqdU·e@üýû$ `]- ò " 400 -
[06/Sep/2024 23:43:58,895] - Broken pipe from ('167.94.145.103', 39860)
[06/Sep/2024 23:44:02] "GET / HTTP/1.1" 200 7759
[06/Sep/2024 23:44:02,827] - Broken pipe from ('167.94.145.103', 39974)
[06/Sep/2024 23:44:06] "GET / HTTP/1.1" 200 7759
Not Found: /favicon.ico
[06/Sep/2024 23:44:07] "GET /favicon.ico HTTP/1.1" 404 2442
[06/Sep/2024 23:44:07] code 505, message Invalid HTTP version (2.0)
[06/Sep/2024 23:44:07] "PRI * HTTP/2.0" 505 -
[06/Sep/2024 23:55:44] code 400, message Bad request version ('ð¤e\x02\x03\x01\x00\x01')
[06/Sep/2024 23:55:44] "   àZ          =K    |¨À PV¦9þ                                                 0 »íËGPb¡B3ÈÅÔö*ÃFÇ0ÙJ|k([¦Ï¡5)JxÖÁFøZ¢Ö)Ù@ðuYéâÂ'×¹7¿ä³bã­ñA;ª¯"7[Ý<Pýaì3ª`X·Ø¨¢õE8k'ABî¾s#ò¥C×+8åpð¤e " 400 -
Not Found: /aaa9
[07/Sep/2024 00:42:35] "GET /aaa9 HTTP/1.1" 404 2421
Not Found: /aab8
[07/Sep/2024 00:42:36] "GET /aab8 HTTP/1.1" 404 2421
[07/Sep/2024 00:42:38] "GET / HTTP/1.1" 200 7759
Not Found: /.env
[07/Sep/2024 03:14:32] "GET /.env HTTP/1.1" 404 2421
[07/Sep/2024 07:16:15] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x03_¯æ\x8cÎÄyÕf\x18ªóU$'¡\x0f\x98\x13Ü\x01eÌ»mÎâ\x82\x00Ûú\x00\x00\x1aÀ/À+À\x11À\x07À\x13À")
[07/Sep/2024 07:16:15] You're accessing the development server over HTTPS, but it only supports HTTP.
[07/Sep/2024 08:57:31] code 400, message Bad request version ('À\x13À')
[07/Sep/2024 08:57:31] You're accessing the development server over HTTPS, but it only supports HTTP.
[07/Sep/2024 08:57:31] "GET / HTTP/1.1" 200 7759
[07/Sep/2024 17:06:21] "GET / HTTP/1.1" 200 7759
[07/Sep/2024 19:10:20] code 400, message Bad request version ('À\x14À')
[07/Sep/2024 19:10:20] You're accessing the development server over HTTPS, but it only supports HTTP.
[07/Sep/2024 20:31:58,565] - Broken pipe from ('104.152.52.148', 41075)
[07/Sep/2024 21:38:52,339] - Broken pipe from ('199.45.155.66', 40566)
[07/Sep/2024 21:38:55] "GET / HTTP/1.1" 200 7759
[07/Sep/2024 21:38:56,024] - Broken pipe from ('199.45.155.66', 40580)
[07/Sep/2024 21:38:59] "GET / HTTP/1.1" 200 7759
Not Found: /favicon.ico
[07/Sep/2024 21:39:00] "GET /favicon.ico HTTP/1.1" 404 2442
[07/Sep/2024 21:39:01] code 505, message Invalid HTTP version (2.0)
[07/Sep/2024 21:39:01] "PRI * HTTP/2.0" 505 -
Not Found: /.env
[07/Sep/2024 23:20:04] "GET /.env HTTP/1.1" 404 2421
[08/Sep/2024 01:22:14] "GET / HTTP/1.1" 200 7759
[08/Sep/2024 02:12:36] code 400, message Bad request syntax ('MGLNDD_3.38.84.194_8000')
[08/Sep/2024 02:12:36] "MGLNDD_3.38.84.194_8000" 400 -
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Error: That port is already in use.
[08/Sep/2024 06:17:11] "GET /myapp/answer/create/305/ HTTP/1.1" 200 2820
[08/Sep/2024 06:17:11] "GET /static/style.css HTTP/1.1" 200 0
[08/Sep/2024 06:17:11] "GET /static/bootstrap.min.css HTTP/1.1" 200 163873
[08/Sep/2024 06:17:13] "GET /admin/ HTTP/1.1" 200 7241
[08/Sep/2024 06:17:14] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
[08/Sep/2024 06:17:14] "GET /static/admin/css/base.css HTTP/1.1" 200 21310
[08/Sep/2024 06:17:14] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[08/Sep/2024 06:17:14] "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
[08/Sep/2024 06:17:14] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
[08/Sep/2024 06:17:14] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
[08/Sep/2024 06:17:14] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[08/Sep/2024 06:17:14] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[08/Sep/2024 06:17:14] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[08/Sep/2024 06:37:02] "GET /myapp/ HTTP/1.1" 200 7670
[08/Sep/2024 06:37:02] "GET /common/logout/ HTTP/1.1" 302 0
[08/Sep/2024 06:37:02] "GET / HTTP/1.1" 200 7759
[08/Sep/2024 06:37:03] "GET / HTTP/1.1" 200 7759
[08/Sep/2024 06:37:06] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:07] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:07] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:07] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:07] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:08] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:08] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:37:08] "GET / HTTP/1.1" 200 7830
[08/Sep/2024 06:38:40] "GET / HTTP/1.1" 200 8769
[08/Sep/2024 06:38:42] "GET / HTTP/1.1" 200 8769
[08/Sep/2024 06:41:24] "GET /myapp/myapp/305/ HTTP/1.1" 200 2917
[08/Sep/2024 06:41:56] "GET /myapp/myapp/305/ HTTP/1.1" 200 2965
[08/Sep/2024 06:41:57] "GET /myapp/myapp/305/ HTTP/1.1" 200 2965
[08/Sep/2024 06:42:02] "GET /myapp/myapp/304/ HTTP/1.1" 200 3314
[08/Sep/2024 06:42:19] "GET /myapp/myapp/304/ HTTP/1.1" 200 3363
[08/Sep/2024 06:42:20] "GET /myapp/myapp/304/ HTTP/1.1" 200 3363
[08/Sep/2024 06:52:21] code 400, message Bad request syntax ('\x16\x03\x01\x00u\x01\x00\x00q\x03\x03R\x0f\x06Þz&q±I')
[08/Sep/2024 06:52:21] You're accessing the development server over HTTPS, but it only supports HTTP.
[08/Sep/2024 08:23:20] code 400, message Bad request version ('À\x14À')
[08/Sep/2024 08:23:20] You're accessing the development server over HTTPS, but it only supports HTTP.
[08/Sep/2024 08:57:27] "GET / HTTP/1.1" 200 8769
Not Found: /.env
[08/Sep/2024 11:20:37] "GET /.env HTTP/1.1" 404 2421
/home/ec2-user/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 08, 2024 - 12:26:49
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[08/Sep/2024 12:28:08] "GET /myapp/myapp/304/ HTTP/1.1" 200 3418
[08/Sep/2024 12:28:08] "GET /static/style.css HTTP/1.1" 200 0
[08/Sep/2024 12:28:08] "GET /static/bootstrap.min.css HTTP/1.1" 200 163873
[08/Sep/2024 12:28:10] "GET /myapp/myapp/304/ HTTP/1.1" 200 3418
[08/Sep/2024 12:28:12] "GET /myapp/ HTTP/1.1" 200 8769
[08/Sep/2024 12:28:12] "GET /common/login/ HTTP/1.1" 200 2558
[08/Sep/2024 12:28:15] "POST /common/login/ HTTP/1.1" 302 0
[08/Sep/2024 12:28:15] "GET / HTTP/1.1" 200 8680
Internal Server Error: /myapp/myapp/304/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'pybo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/myapp/views.py", line 22, in detail
    return render(request, 'myapp/question_detail.html', context)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'pybo' is not a registered namespace
[08/Sep/2024 12:28:17] "GET /myapp/myapp/304/ HTTP/1.1" 500 177111
[08/Sep/2024 12:28:23] "GET / HTTP/1.1" 200 8680
Internal Server Error: /myapp/myapp/304/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/myapp/views.py", line 22, in detail
    return render(request, 'myapp/question_detail.html', context)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'question_modify' not found. 'question_modify' is not a valid view function or pattern name.
[08/Sep/2024 12:28:24] "GET /myapp/myapp/304/ HTTP/1.1" 500 175919
Internal Server Error: /myapp/myapp/304/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/myapp/views.py", line 22, in detail
    return render(request, 'myapp/question_detail.html', context)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'question_modify' not found. 'question_modify' is not a valid view function or pattern name.
[08/Sep/2024 12:28:26] "GET /myapp/myapp/304/ HTTP/1.1" 500 176056
/home/ec2-user/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/myproject/urls.py", line 26, in <module>
    path('myapp/', include('myapp.urls')),
  File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/myapp/urls.py", line 28, in <module>
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
AttributeError: module 'myapp.views' has no attribute 'question_modify'
/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/myproject/urls.py", line 26, in <module>
    path('myapp/', include('myapp.urls')),
  File "/usr/local/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/myapp/urls.py", line 28, in <module>
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
AttributeError: module 'myapp.views' has no attribute 'question_modify'
/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 08, 2024 - 12:29:36
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

/home/ec2-user/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 08, 2024 - 12:30:02
Django version 4.2.15, using settings 'myproject.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[08/Sep/2024 12:30:02] "GET / HTTP/1.1" 200 8680
[08/Sep/2024 12:30:06] "GET /myapp/myapp/304/ HTTP/1.1" 200 3452
[08/Sep/2024 12:30:07] "GET /myapp/question/modify/304/ HTTP/1.1" 200 2479
[08/Sep/2024 12:30:17] "GET /myapp/myapp/305/ HTTP/1.1" 200 2923
[08/Sep/2024 12:30:20] "GET /myapp/myapp/300/ HTTP/1.1" 200 3469
